title: TypoGodfrey
description: Thomas Godfrey's Typography blog
footer_text: Copyright 2021 Thomas Godfrey
header_feature_image: ../uploads/typo-blog-banner-2.png
header_text: ""
header_text_color: "#ffffff"
bannerheight: 20vmax
navbarheight: 55px
logo: ../uploads/typo-2.png
favicon: ../uploads/typo-2.png
gridlayout: false
fixednavbar: true
upzoom: true
items: []
